pull_request_rules:
    - name: Automatic merge on approval
      conditions:
          - check-success=Node 14.x on windows-latest
          - check-success=Node 14.x on macOS-latest
          - check-success=Node 15.x on ubuntu-latest
          - check-success=Node 15.x on windows-latest
          - check-success=Node 15.x on macOS-latest
          - check-success=Node 16.x on ubuntu-latest
          - check-success=Node 16.x on windows-latest
          - check-success=Node 16.x on macOS-latest

          - label=dependencies
      actions:
          merge:
              method: merge
